In [239]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

1.1 Consider the daily stock returns of American Express (AXP), Caterpillar(CAT), and Starbucks (SBUX) from January 1999 to December 2008. The data are simple returns given in the ﬁle `d-3stocks9908.txt` (date, axp, cat, sbux).

In [240]:
df = pd.read_csv("data/d-3stocks9908.txt", sep=r"\s+")
stocks = df.columns[1:]
df.head()

       date       axp       cat      sbux
0  19990104 -0.009756  0.029891 -0.040089
1  19990105 -0.019089 -0.002639 -0.034803
2  19990106  0.043063  0.026455 -0.008413
3  19990107  0.012063  0.009021  0.003636
4  19990108  0.030393  0.042146  0.021739

1. Express the simple returns in percentages. Compute the sample mean, standard deviation, skewness, excess kurtosis, minimum, and maximum of the percentage simple returns.

In [241]:
ret_pct = df[stocks] * 100
pd.DataFrame({
    'mean': ret_pct.mean(),
    'std': ret_pct.std(ddof=1),
    'skewness': ret_pct.apply(skew),
    'excess_kurtosis': ret_pct.apply(lambda x: kurtosis(x, fisher=True)),
    'min': ret_pct.min(),
    'max': ret_pct.max()
}).T

                       axp        cat       sbux
mean              0.014565   0.059504   0.048054
std               2.446218   2.169648   2.682622
skewness         -0.034627   0.011678  -0.082476
excess_kurtosis   6.055251   4.459195   8.754924
min             -17.594900 -14.517500 -28.286200
max              17.926600  14.722900  14.635400

2. Transform the simple returns to log returns.

In [242]:
log_ret_pct = np.log(df[stocks] + 1) * 100
log_ret_pct

           axp       cat      sbux
0    -0.980390  2.945297 -4.091471
1    -1.927355 -0.264249 -3.542305
2     4.216158  2.611112 -0.844859
3     1.199082  0.898055  0.362941
4     2.994028  4.128205  2.150608
...        ...       ...       ...
2510  0.055684  1.878642  1.619023
2511 -0.334459  1.914261  0.107043
2512 -1.179428 -0.893480 -3.482439
2513  1.680697  3.069990  3.589307
2514  3.009846  2.286949  1.062733

[2515 rows x 3 columns]

3. Express the log returns in percentages. Compute the sample mean, standard deviation, skewness, excess kurtosis, minimum, and maximum of the percentage log returns.

In [243]:
state = pd.DataFrame(
    {
        "mean": log_ret_pct.mean(),
        "std": log_ret_pct.std(ddof=0),
        "skewness": log_ret_pct.apply(skew),
        "excess_kurtosis": log_ret_pct.apply(lambda x: kurtosis(x, fisher=True)),
        "min": log_ret_pct.min(),
        "max": log_ret_pct.max(),
    }
)
state.T

                       axp        cat       sbux
mean             -0.015434   0.035949   0.011885
std               2.452410   2.171051   2.695352
skewness         -0.336635  -0.201865  -0.597424
excess_kurtosis   6.494046   4.700869  12.908121
min             -19.352286 -15.685851 -33.248699
max              16.489221  13.734947  13.658647

4. Test the null hypothesis that the mean of the log returns of each stock is zero. That is, perform three separate tests. Use 5% signiﬁcance level to draw your conclusion.

In [244]:
print("Reject H0?: ")
critical = 1.96  # Z0.95
np.abs(state["mean"] / (state["std"] / len(df) ** 0.5)) > critical

Reject H0?:

axp     False
cat     False
sbux    False
dtype: bool

1.4. Consider the daily log returns of American Express stock from January 1999 to December 2008 as in Exercise 1.1. Use the 5% signiﬁcance level to perform the following tests:

In [245]:
axp = state.loc["axp"]
axp.head()

mean               -0.015434
std                 2.452410
skewness           -0.336635
excess_kurtosis     6.494046
min               -19.352286
Name: axp, dtype: float64

1. Test the null hypothesis that the skewness measure of the returns is zero.

In [246]:
print(f"Reject H0?: {axp['skewness'] / (6 / len(df)) ** 0.5 > critical}")

Reject H0?: False

2. Test the null hypothesis that the excess kurtosis of the returns is zero.

In [255]:
print(f"Reject H0?: {axp['excess_kurtosis'] / (24 / len(df)) ** 0.5 > critical}")

Reject H0?: True

1.2. Answer the same questions as in Exercise 1.1 but using monthly stock returns for General Motors (GM), CRSP value-weighted index (VW), CRSP equalweighted index (EW), and S&P composite index from January 1975 to December 2008. The returns of the indexes include dividend distributions. Data ﬁle is `m-gm3dx7508.txt` (date, gm, vw, ew, sp).

In [248]:
df = pd.read_csv("data/m-gm3dx7508.txt", sep=r"\s+")
stocks = df.columns[1:]
df.head()

       date        gm        vw        ew        sp
0  19750131  0.252033  0.141600  0.299260  0.122812
1  19750228  0.028571  0.058411  0.053918  0.059886
2  19750331  0.054487  0.030191  0.081497  0.021694
3  19750430  0.045593  0.046497  0.031093  0.047265
4  19750530  0.037209  0.055140  0.072876  0.044101

1. Express the simple returns in percentages. Compute the sample mean, standard deviation, skewness, excess kurtosis, minimum, and maximum of the percentage simple returns.

In [249]:
ret_pct = df[stocks] * 100
pd.DataFrame({
    'mean': ret_pct.mean(),
    'std': ret_pct.std(ddof=1),
    'skewness': ret_pct.apply(skew),
    'excess_kurtosis': ret_pct.apply(lambda x: kurtosis(x, fisher=True)),
    'min': ret_pct.min(),
    'max': ret_pct.max()
}).T

                        gm         vw         ew         sp
mean              0.556755   1.011799   1.331385   0.730084
std               9.272704   4.507473   5.595899   4.359929
skewness         -0.384889  -0.745401  -0.301230  -0.572649
excess_kurtosis   2.072913   2.693909   4.369746   2.294522
min             -38.931300 -22.536300 -27.224800 -21.763000
max              27.661900  14.160000  29.926000  13.176700

2. Transform the simple returns to log returns.

In [250]:
log_ret_pct = np.log(df[stocks] + 1) * 100
log_ret_pct

            gm         vw         ew         sp
0    22.476863  13.243079  26.179487  11.583625
1     2.817046   5.676873   5.251465   5.816136
2     5.305439   2.974422   7.834619   2.146203
3     4.458419   4.544840   3.061940   4.618200
4     3.653345   5.367346   7.034289   4.315623
..         ...        ...        ...        ...
403 -10.165406   1.098148   1.396799   1.211729
404  -5.657035 -10.320728 -12.884297  -9.518029
405 -48.988312 -20.423103 -23.067686 -18.563705
406  -9.981039  -8.905638 -14.687372  -7.779831
407 -49.317073   2.125451   4.218075   0.779157

[408 rows x 4 columns]

3. Express the log returns in percentages. Compute the sample mean, standard deviation, skewness, excess kurtosis, minimum, and maximum of the percentage log returns.

In [251]:
state = pd.DataFrame(
    {
        "mean": log_ret_pct.mean(),
        "std": log_ret_pct.std(ddof=0),
        "skewness": log_ret_pct.apply(skew),
        "excess_kurtosis": log_ret_pct.apply(lambda x: kurtosis(x, fisher=True)),
        "min": log_ret_pct.min(),
        "max": log_ret_pct.max(),
    }
)
state.T

                        gm         vw         ew         sp
mean              0.110182   0.904567   1.166997   0.631937
std               9.578516   4.554993   5.619083   4.396808
skewness         -1.027439  -1.054877  -0.839217  -0.857996
excess_kurtosis   4.055294   3.971681   5.283005   3.365860
min             -49.317073 -25.536075 -31.779495 -24.542750
max              24.421518  13.243079  26.179487  12.378013

4. Test the null hypothesis that the mean of the log returns of each stock is zero. That is, perform three separate tests. Use 5% signiﬁcance level to draw your conclusion.

In [252]:
print("Reject H0?: ")
critical = 1.96
np.abs(state["mean"] / (state["std"] / len(df) ** 0.5)) > critical

Reject H0?:

gm    False
vw     True
ew     True
sp     True
dtype: bool

1.3. Consider the monthly stock returns of S&P composite index from January 1975 to December 2008 in Exercise 1.2. Answer the following questions:
1. What is the average annual log return over the data span?

In [253]:
sp_log_ret = log_ret_pct["sp"]

(np.exp(np.reshape(sp_log_ret, [-1, 12]).mean(axis=1)) - 1).mean()

np.float64(2.5070807836431466)

2. Assume that there were no transaction costs. If one invested $1.00 on the S&P composite index at the beginning of 1975, what was the value of the investment at the end of 2008?

In [254]:
np.exp(sp_log_ret.sum())

np.float64(9.425796823244669e+111)